apiVersion: hive.openshift.io/v1
kind: SyncSet
metadata:
  name: {{ include "skupper-hub-bridge.fullname" . }}-syncset
  labels:
    {{- include "skupper-hub-bridge.labels" . | nindent 4 }}
spec:
  clusterDeploymentRefs:
  - name: {{ include "skupper-hub-bridge.clusterName" . }}
  resourceApplyMode: Sync
  applyBehavior: CreateOrUpdate
  enablePatchTemplates: false
  enableResourceTemplates: false

  patches:
    - kind: DNS
      apiVersion: operator.openshift.io/v1
      name: default
      patch: |-
        {"spec": {
          "servers": [
            {
              "name": "hub-dns",
              "zones": [{{ .Values.dns.zone | quote }}],
              "forwardPlugin": {
                "policy": "Random",
                "protocolStrategy": "TCP",
                "upstreams": [{{ .Values.dns.serviceIP | quote }}]
              }
            }
          ]
        }}
      patchType: merge

  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: hub-link
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: coredns
        namespace: hub-link
        labels:
          k8s-app: hub-dns
          app.kubernetes.io/name: coredns
      data:
        Corefile: |
          .:53 {
              errors
              log . {
                  class error
              }
              health {
                lameduck 5s
              }
              ready

              # Explicitly handle AAAA - return empty response
              template IN AAAA {{ .Values.dns.zone }} {
                  match ".*\.{{ include "skupper-hub-bridge.escapedZone" . }}\.$"
                  rcode NOERROR
              }
              # today this doesn't do anything, we aren't forwarding 80/443 to the hub ingress router
              rewrite name regex (.*\.apps\.{{ include "skupper-hub-bridge.escapedZone" . }}) hub-kubernetes.hub-link.svc.cluster.local answer auto
              rewrite name exact api.{{ .Values.dns.zone }} hub-kubernetes.hub-link.svc.cluster.local
              forward . {{ .Values.dns.upstreamIP }}
              prometheus :9153
          }
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hub-dns-forwarder
        namespace: hub-link
        labels:
          k8s-app: hub-dns
          app.kubernetes.io/name: coredns
      spec:
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
        selector:
          matchLabels:
            k8s-app: hub-dns
            app.kubernetes.io/name: coredns
        template:
          metadata:
            labels:
              k8s-app: hub-dns
              app.kubernetes.io/name: coredns
          spec:
            priorityClassName: system-cluster-critical
            serviceAccountName: default
            tolerations:
              - key: "CriticalAddonsOnly"
                operator: "Exists"
            nodeSelector:
              kubernetes.io/os: linux
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: k8s-app
                          operator: In
                          values: ["hub-dns"]
                    topologyKey: kubernetes.io/hostname
            containers:
              - name: coredns
                image: coredns/coredns:1.12.0
                imagePullPolicy: IfNotPresent
                resources:
                  # disabling until we know more about how much we need
                  # limits:
                  #   memory: 170Mi
                  requests:
                    cpu: 100m
                    memory: 70Mi
                args: ["-conf", "/etc/coredns/Corefile"]
                volumeMounts:
                  - name: config-volume
                    mountPath: /etc/coredns
                    readOnly: true
                ports:
                  - containerPort: 53
                    name: dns
                    protocol: UDP
                  - containerPort: 53
                    name: dns-tcp
                    protocol: TCP
                  - containerPort: 9153
                    name: metrics
                    protocol: TCP
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    add:
                      - NET_BIND_SERVICE
                    drop:
                      - all
                  readOnlyRootFilesystem: true
                livenessProbe:
                  httpGet:
                    path: /health
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 60
                  timeoutSeconds: 5
                  successThreshold: 1
                  failureThreshold: 5
                readinessProbe:
                  httpGet:
                    path: /ready
                    port: 8181
                    scheme: HTTP
            volumes:
              - name: config-volume
                configMap:
                  name: coredns
                  items:
                    - key: Corefile
                      path: Corefile
    - apiVersion: v1
      kind: Service
      metadata:
        name: hub-dns
        namespace: hub-link
        # annotations:
        #   prometheus.io/port: "9153"
        #   prometheus.io/scrape: "true"
        labels:
          k8s-app: hub-dns
          app.kubernetes.io/name: coredns
      spec:
        selector:
          k8s-app: hub-dns
          app.kubernetes.io/name: coredns
        clusterIP: {{ .Values.dns.serviceIP }}
        ports:
          - name: dns
            port: 53
            protocol: UDP
          - name: dns-tcp
            port: 53
            protocol: TCP
          - name: metrics
            port: 9153
            protocol: TCP

    # ---

    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: skupper-operator
        namespace: openshift-operators
      spec:
        channel: stable-2
        installPlanApproval: Automatic
        name: skupper-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
    - apiVersion: skupper.io/v2alpha1
      kind: Site
      metadata:
        name: site
        namespace: hub-link
      spec:
        linkAccess: route
    - apiVersion: skupper.io/v2alpha1
      kind: AccessGrant
      metadata:
        name: hub-grant
        namespace: hub-link
      spec:
        expirationWindow: 12h
        redemptionsAllowed: 5
    - apiVersion: skupper.io/v2alpha1
      kind: Listener
      metadata:
        name: hub-kubernetes
        namespace: hub-link
      spec:
        routingKey: hub-kubernetes
        host: hub-kubernetes
        port: 6443
